const getters = {
  role: state => state.user.role,
  etc: state => state.etc.etcOrigin,
  loading: state => state.app.loading,
  work_id: state => state.job.work_id,
  profile: state => state.user.profile,
  language: state => state.app.language,
  tabIndex: state => state.app.tabIndex,
  name: state => state.user.profile.name,
  token: state => state.user.access_token,
  email: state => state.user.profile.email,
  routes: state => state.permission.routes,
  permission: state => state.user.permission,
  isReload: state => state.permission.isReload,
  message_id: state => state.message.message_id,
  expToken: state => state.user.profile.expToken,
  addRoutes: state => state.permission.addRoutes,
  listUser: state => state.userManagement.listUser,
  permissionCheck: state => state.user.profile.type,
  is_filled_data: state => state.job.is_filled_data,
  permissionRoutes: state => state.permission.routes,
  degitacho: state => state.degitacho.degitachoOrigin,
  list_selected_hr: state => state.job.list_selected_hr,
  list_disabled_hr: state => state.job.list_disabled_hr,
  currentRoutes: state => state.permission.currentRoutes,
  job_search_data: state => state.jobSearch.job_search_data,
  searchParams: state => state.hrSearchQuery.searchParams,
  list_hr_information: state => state.job.list_hr_information,
  setOpen: state => state.app.setOpen,
  routerInfo: state => state.routerParam.routerInfo,
  revertRouter: state => state.routerParam.revertRouter,
};

export default getters;
