<?php

define('DEFAULT_ZERO_PAD', 5);
define('DEFAULT_STR_ZERO', '0');

define('CODE_SUCCESS', 200);
define('CODE_CREATE_FAILED', 201);
define('CODE_DELETE_FAILED', 202);
define('CODE_MULTI_STATUS', 207);
define('CODE_NO_ACCESS', 403);
define('CODE_NOT_FOUND', 404);
define('CODE_ERROR_SERVER', 500);
define('CODE_UNAUTHORIZED', 401);
define('HTTP_FORBIDDEN', 403);
define('HTTP_UNPROCESSABLE_ENTITY', 422);

define('IMAGE', 'upload/image');

define('JOB_TYPE', 1);
define('MAJOR_CLASSIFICATION', 2);

define('EXAMINATION_PENDING', 1);
define('CONFIRM', 2);
define('REJECT', 3);
define('STOP_USING', 4);

define('SUPER_ADMIN', 1);
define('COMPANY_MANAGER', 2);
define('HR_MANAGER', 3);
define('COMPANY', 4);
define('HR', 5);

const PERMISSION_NAME = [
    SUPER_ADMIN => 'システム管理者',
    COMPANY_MANAGER => '企業管理',
    HR_MANAGER => '運営事務局',
];

define('ACC_PUBLIC', 1);
define('ACC_PRIVATE', 2);
define('ACC_OFFICIAL_OFFER_CONFIRM', 3);

const TYPE_NOTIFY = [
    'register_company' => 1,
    'register_hr' => 2,
    'remind_account' => 3
];


//define work table
const WORK_FULL_TIME_EMPLOYEE = 1;
const WORK_CONTRACT_EMPLOYEE = 2;
const WORK_TEMPORARY_EMPLOYEE = 3;
const WORK_OTHER_EMPLOYEE = 4;

const WORK_CONFIRM_YES = 1;
const WORK_CONFIRM_NO = 2;

const WORK_FIRST_INTERVIEW = 1;
const WORK_SECOND_INTERVIEW = 2;
const WORK_THIRD_INTERVIEW = 3;
const WORK_FOURTH_INTERVIEW = 4;
const WORK_FIFTH_INTERVIEW = 5;

const WORK_STATUS_RECRUITING = 1;
const WORK_STATUS_PAUSED = 2;
const WORK_STATUS_OUT_OF_RECRUITMENT_PERIOD = 3;
//end define work

//entry table
const ENTRY_STATUS_REQUESTING = 1;
const ENTRY_STATUS_REJECT = 2;
const ENTRY_STATUS_DECLINE = 3;
const ENTRY_STATUS_CONFIRM = 4;
const ENTRY_STATUS_TEXTS = [
    ENTRY_STATUS_REQUESTING => '申請中',
    ENTRY_STATUS_REJECT => '却下',
    ENTRY_STATUS_DECLINE => '辞退',
    ENTRY_STATUS_CONFIRM => '承認'
];

const WHY_REJECTS = [
    1 => '他社内定',
    2 => '就業継続（転職断念）',
    3 => '条件不一致（年収）',
    4 => '条件不一致（勤務地）',
    5 => '条件不一致（その他待遇）',
    6 => '就業環境',
    7 => '家族の反対',
    8 => '在留資格不一致',
    9 => '本人との連絡不通',
    10 => 'その他'
];

//hrs table
const HRS_STATUS_PUBLIC = 1;
const HRS_STATUS_PRIVATE = 2;
const HRS_STATUS_CONFIRM = 3;

const HRS_STATUS_TEXTS = [
    HRS_STATUS_PUBLIC => '公開',
    HRS_STATUS_PRIVATE => '非公開',
    HRS_STATUS_CONFIRM => '内定承諾'
];

const HRS_GENDER_MALE = 1;
const HRS_GENDER_FEMALE = 2;

const HRS_FULL_TIME_EMPLOYEE = 1;
const HRS_CONTRACT_EMPLOYEE = 2;
const HRS_TEMPORARY_EMPLOYEE = 3;
const HRS_OTHER_EMPLOYEE = 4;

const HRS_WORK_FORM = [
    HRS_FULL_TIME_EMPLOYEE, // 'Full-time employee',
    HRS_CONTRACT_EMPLOYEE, // 'Contract employee',
    HRS_TEMPORARY_EMPLOYEE, // 'Temporary employee',
    HRS_OTHER_EMPLOYEE, // 'Others'
];

const HRS_WORK_FORM_TEXT = [
    HRS_FULL_TIME_EMPLOYEE => '正社員', // 'Full-time employee',
    HRS_CONTRACT_EMPLOYEE => '契約社員', // 'Contract employee',
    HRS_TEMPORARY_EMPLOYEE => '派遣社員', // 'Temporary employee',
    HRS_OTHER_EMPLOYEE => 'その他', // 'Others'
];

const HRS_CLASSIFICATION_GRADUATION = 1;
const HRS_CLASSIFICATION_DROPOUT = 2;
const HRS_CLASSIFICATION_FINISH = 3;

const HR_FINAL_EDUCATION = [
    HRS_CLASSIFICATION_GRADUATION,
    HRS_CLASSIFICATION_DROPOUT,
    HRS_CLASSIFICATION_FINISH
];

const HR_FINAL_EDUCATION_TEXT = [
    HRS_CLASSIFICATION_GRADUATION => '卒業',
    HRS_CLASSIFICATION_DROPOUT => '中退',
    HRS_CLASSIFICATION_FINISH => '卒業見込み'
];

const HR_EDUCATION_DEGREES = [
    1 => '博士',
    2 => '修士',
    3 => '学士',//tren dai hoc
    4 => '短期大学卒業',
    5 => '専門学校卒業',
    6 => '高校卒業'//duoi dai hoc
];

const HR_EDUCATION_DEGREES_TYPE = [
    'university_or_more' => 1,
    'aside_from_university' => 2
];

const HR_JAPANESE_LEVEL = [
    1 => 'N1',
    2 => 'N2',
    3 => 'N3',
    4 => 'N4',
    5 => 'N5',
    6 => '資格なし'
];

//result table
const RESULT_STATUS_SELECTION_OFFER = 1;
const RESULT_STATUS_SELECTION_NOT_PASS = 2;
const RESULT_STATUS_SELECTION_OFFER_CONFIRM = 3;
const RESULT_STATUS_SELECTION_OFFER_DECLINE = 4;
const RESULT_STATUS_LIST = [
    RESULT_STATUS_SELECTION_OFFER => '内定',
    RESULT_STATUS_SELECTION_NOT_PASS => '不合格',
    RESULT_STATUS_SELECTION_OFFER_CONFIRM => '内定承諾',
    RESULT_STATUS_SELECTION_OFFER_DECLINE => '内定辞退'
];

const RESULT_STATUS_PERIOD_EXPIRATION = 1;
const RESULT_STATUS_PERIOD_DATE = 2;

//offer table
const OFFER_STATUS_REQUESTING = 1;
const OFFER_STATUS_DECLINE = 2;
const OFFER_STATUS_CONFIRM = 3;

const OFFER_STATUS_TEXTS = [
    OFFER_STATUS_REQUESTING => '申請中',
    OFFER_STATUS_DECLINE => '辞退',
    OFFER_STATUS_CONFIRM => '承認',
];


//interview
const INTERVIEW_TYPE_GROUP = 1;
const INTERVIEW_TYPE_PRIVATE = 2;


const INTERVIEW_TABLE_STEP_INTERVIEW = 3;
const INTERVIEW_TABLE_STEP_RESULT = 4;
const INTERVIEW_TYPE_TEXTS = [
    INTERVIEW_TYPE_GROUP => '集団面接',
    INTERVIEW_TYPE_PRIVATE => '個人面接'
];

const INTERVIEW_STATUS_SELECTION_DOC_PASS = 1;
const INTERVIEW_STATUS_SELECTION_OFFER_CONFIRM = 2;
const INTERVIEW_STATUS_SELECTION_INTERVIEW_CANCEL = 3;
const INTERVIEW_STATUS_SELECTION_INTERVIEW_DECLINE = 4;
const INTERVIEW_STATUS_SELECTION_FIRST_PASS = 5;
const INTERVIEW_STATUS_SELECTION_SECOND_PASS = 6;
const INTERVIEW_STATUS_SELECTION_THIRD_PASS = 7;
const INTERVIEW_STATUS_SELECTION_FOURTH_PASS = 8;
const INTERVIEW_STATUS_SELECTION_FIFTH_PASS = 9;
//const INTERVIEW_STATUS_SELECTION_SIX_PASS = 10;
//const INTERVIEW_STATUS_SELECTION_SEVEN_PASS = 11;
//const INTERVIEW_STATUS_SELECTION_EIGHT_PASS = 12;
//const INTERVIEW_STATUS_SELECTION_NINE_PASS = 13;
//const INTERVIEW_STATUS_SELECTION_TEN_PASS = 14;

const STATUS_SELECTIONS = [
    INTERVIEW_STATUS_SELECTION_DOC_PASS => '書類通過',
    INTERVIEW_STATUS_SELECTION_OFFER_CONFIRM => 'オファー承諾',
    INTERVIEW_STATUS_SELECTION_INTERVIEW_CANCEL => '面接中止',
    INTERVIEW_STATUS_SELECTION_INTERVIEW_DECLINE => '面接辞退',
    INTERVIEW_STATUS_SELECTION_FIRST_PASS => '一次合格',
    INTERVIEW_STATUS_SELECTION_SECOND_PASS => '二次合格',
    INTERVIEW_STATUS_SELECTION_THIRD_PASS => '三次合格',
    INTERVIEW_STATUS_SELECTION_FOURTH_PASS => '四次合格',
    INTERVIEW_STATUS_SELECTION_FIFTH_PASS => '五次合格',
    //    INTERVIEW_STATUS_SELECTION_SIX_PASS => '次合格',
    //    INTERVIEW_STATUS_SELECTION_SEVEN_PASS => '次合格',
    //    INTERVIEW_STATUS_SELECTION_EIGHT_PASS => '次合格',
    //    INTERVIEW_STATUS_SELECTION_NINE_PASS => '次合格',
    //    INTERVIEW_STATUS_SELECTION_TEN_PASS => '次合格',
];

const INTERVIEW_STATUS_INTERVIEW_ADJUSTMENT_BEFORE_ADJUSTMENT = 1;
const INTERVIEW_STATUS_INTERVIEW_ADJUSTMENT_ADJUSTING = 2;
const INTERVIEW_STATUS_INTERVIEW_ADJUSTMENT_URL_SETTING = 3;
const INTERVIEW_STATUS_INTERVIEW_ADJUSTMENT_ADJUSTED = 4;

const STATUS_ADJUSTINGS = [
    INTERVIEW_STATUS_INTERVIEW_ADJUSTMENT_BEFORE_ADJUSTMENT => '調整前',
    INTERVIEW_STATUS_INTERVIEW_ADJUSTMENT_ADJUSTING => '調整中',
    INTERVIEW_STATUS_INTERVIEW_ADJUSTMENT_URL_SETTING => 'URL設定中',
    INTERVIEW_STATUS_INTERVIEW_ADJUSTMENT_ADJUSTED => '調整済',
];

//Cấu hình các hình thức review

const INTERVIEW_STATUS_REVIEW_PASS = 1;
const INTERVIEW_STATUS_REVIEW_NO_PASS = 2;
const INTERVIEW_STATUS_REVIEW_OFFICIAL_OFFER = 3;

const INTERVIEW_STATUS_REVIEW = [
    INTERVIEW_STATUS_REVIEW_PASS,
    INTERVIEW_STATUS_REVIEW_NO_PASS,
    INTERVIEW_STATUS_REVIEW_OFFICIAL_OFFER,
];

// Cấu hình option vòng phỏng vấn review

const OPTION_PASS_OPERATION_FIRST = 1;
const OPTION_PASS_OPERATION_SECOND = 2;
const OPTION_PASS_OPERATION_THIRD = 3;
const OPTION_PASS_OPERATION_FOURTH = 4;
const REVIEW_PASS_OPERATION_FINAL = 5;

const OPTION_PASS_OPERATION = [
    OPTION_PASS_OPERATION_FIRST,
    OPTION_PASS_OPERATION_SECOND,
    OPTION_PASS_OPERATION_THIRD,
    OPTION_PASS_OPERATION_FOURTH,
    REVIEW_PASS_OPERATION_FINAL
];

// cấu hình trạng thái interview_info
const INTERVIEW_INFO_STATUS_TEMPORARY = 1;
const INTERVIEW_INFO_STATUS_HR_CONFIRM = 2;
const INTERVIEW_INFO_STATUS_HR_REJECT = 3;
const INTERVIEW_INFO_STATUS_HR_DECLINE = 4;
const INTERVIEW_INFO_STATUS_HR_SET_URL = 5;
const INTERVIEW_INFO_STATUS_COMPANY_PASS = 6;
const INTERVIEW_INFO_STATUS_COMPANY_NO_PASS = 7;
const INTERVIEW_INFO_STATUS_COMPANY_OFFER = 8;
const INTERVIEW_INFO_STATUS_COMPANY_CONFIRM = 9;
const INTERVIEW_INFO_STATUS_COMPANY_CANCEL = 10;


const INTERVIEW_INFO_STATUS_COMPANY_FIRST = 11;
const INTERVIEW_INFO_STATUS_COMPANY_SECOND = 12;
const INTERVIEW_INFO_STATUS_COMPANY_THIRD = 13;
const INTERVIEW_INFO_STATUS_COMPANY_FOURTH = 14;
const INTERVIEW_INFO_STATUS_COMPANY_FIFTH = 15;

// cấu hình các vòng phỏng vấn

const INTERVIEW_INFO_NUMBER_FIRST = 1;
const INTERVIEW_INFO_NUMBER_SECOND = 2;
const INTERVIEW_INFO_NUMBER_THIRD = 3;
const INTERVIEW_INFO_NUMBER_FOURTH = 4;
const INTERVIEW_INFO_NUMBER_FIFTH = 5;

const INTERVIEW_INFO_NUMBER = [
    INTERVIEW_INFO_NUMBER_FIRST,
    INTERVIEW_INFO_NUMBER_SECOND,
    INTERVIEW_INFO_NUMBER_THIRD,
    INTERVIEW_INFO_NUMBER_FOURTH,
    INTERVIEW_INFO_NUMBER_FIFTH
];

const INTERVIEW_INFO_NUMBER_TEXT_EN = [
    INTERVIEW_INFO_NUMBER_FIRST => 'INTERVIEW_ROUND_ONE',
    INTERVIEW_INFO_NUMBER_SECOND => 'INTERVIEW_ROUND_TWO',
    INTERVIEW_INFO_NUMBER_THIRD => 'INTERVIEW_ROUND_THREE',
    INTERVIEW_INFO_NUMBER_FOURTH => 'INTERVIEW_ROUND_FOUR',
    INTERVIEW_INFO_NUMBER_FIFTH => 'INTERVIEW_ROUND_FIGHT',
];

const INTERVIEW_INFO_NUMBER_TEXT_JA = [
    INTERVIEW_INFO_NUMBER_FIRST => '一次面接',
    INTERVIEW_INFO_NUMBER_SECOND => '二次面接',
    INTERVIEW_INFO_NUMBER_THIRD => '三次面接',
    INTERVIEW_INFO_NUMBER_FOURTH => '四次面接',
//    INTERVIEW_INFO_NUMBER_FIFTH => '五次合格',
    INTERVIEW_INFO_NUMBER_FIFTH => '最終面接',
];

const INTERVIEW_INFO_STATUS = [
    INTERVIEW_INFO_STATUS_TEMPORARY,
    INTERVIEW_INFO_STATUS_HR_CONFIRM,
    INTERVIEW_INFO_STATUS_HR_REJECT,
    INTERVIEW_INFO_STATUS_HR_DECLINE,
    INTERVIEW_INFO_STATUS_HR_SET_URL,
    INTERVIEW_INFO_STATUS_COMPANY_PASS,
    INTERVIEW_INFO_STATUS_COMPANY_NO_PASS,
    INTERVIEW_INFO_STATUS_COMPANY_OFFER,
    INTERVIEW_INFO_STATUS_COMPANY_CONFIRM,
    INTERVIEW_INFO_STATUS_COMPANY_CANCEL,
    INTERVIEW_INFO_STATUS_COMPANY_FIRST,
    INTERVIEW_INFO_STATUS_COMPANY_SECOND,
    INTERVIEW_INFO_STATUS_COMPANY_THIRD,
    INTERVIEW_INFO_STATUS_COMPANY_FOURTH,
    INTERVIEW_INFO_STATUS_COMPANY_FIFTH
];

const INTERVIEW_INFO_STATUS_TEXT_EN = [
    INTERVIEW_INFO_STATUS_TEMPORARY => 'TEMPORARY',
    INTERVIEW_INFO_STATUS_HR_CONFIRM => 'HR_CONFIRM',
    INTERVIEW_INFO_STATUS_HR_REJECT => 'HR_REJECT',
    INTERVIEW_INFO_STATUS_HR_DECLINE => 'HR_DECLINE',
    INTERVIEW_INFO_STATUS_HR_SET_URL => 'HR_SET_URL',
    INTERVIEW_INFO_STATUS_COMPANY_PASS => 'COMPANY_PASS',
    INTERVIEW_INFO_STATUS_COMPANY_NO_PASS => 'COMPANY_NO_PASS',
    INTERVIEW_INFO_STATUS_COMPANY_OFFER => 'COMPANY_OFFER',
    INTERVIEW_INFO_STATUS_COMPANY_CONFIRM => 'COMPANY_CONFIRM',
    INTERVIEW_INFO_STATUS_COMPANY_CANCEL => 'COMPANY_CANCEL',
    INTERVIEW_INFO_STATUS_COMPANY_FIRST => 'FIRST_PASS',
    INTERVIEW_INFO_STATUS_COMPANY_SECOND => 'SECOND_PASS',
    INTERVIEW_INFO_STATUS_COMPANY_THIRD => 'THIRD_PASS',
    INTERVIEW_INFO_STATUS_COMPANY_FOURTH => 'FOURTH_PASS',
    INTERVIEW_INFO_STATUS_COMPANY_FIFTH => 'FIFTH_PASS'
];

const INTERVIEW_INFO_STATUS_TEXT_JA = [
    INTERVIEW_INFO_STATUS_TEMPORARY => '面接候補日',
    INTERVIEW_INFO_STATUS_HR_CONFIRM => '確定',
    INTERVIEW_INFO_STATUS_HR_REJECT => '却下',
    INTERVIEW_INFO_STATUS_HR_DECLINE => '面接辞退',
    INTERVIEW_INFO_STATUS_HR_SET_URL => 'オンライン面接URL',
    INTERVIEW_INFO_STATUS_COMPANY_PASS => '合格',
    INTERVIEW_INFO_STATUS_COMPANY_NO_PASS => '不合格',
    INTERVIEW_INFO_STATUS_COMPANY_OFFER => '内定',
    INTERVIEW_INFO_STATUS_COMPANY_CONFIRM => '確定',
    INTERVIEW_INFO_STATUS_COMPANY_CANCEL => '面接中止',
    INTERVIEW_INFO_STATUS_COMPANY_FIRST => '一次合格',
    INTERVIEW_INFO_STATUS_COMPANY_SECOND => '二次合格',
    INTERVIEW_INFO_STATUS_COMPANY_THIRD => '三次合格',
    INTERVIEW_INFO_STATUS_COMPANY_FOURTH => '四次合格',
    INTERVIEW_INFO_STATUS_COMPANY_FIFTH => '五次合格'
];


const INTERVIEW_INFO_TYPE_GROUP = 1;
const INTERVIEW_INFO_TYPE_PRIVATE = 2;
const INTERVIEW_INFO_TYPE_TEXTS = [
    INTERVIEW_INFO_TYPE_GROUP => '集団面接',
    INTERVIEW_INFO_TYPE_PRIVATE => '個人面接'
];


const CALENDAR_CONFIRMED = 1;
const CALENDAR_DECLINE = 2;

const CALENDAR_TIMELINE_ONE = 1;
const CALENDAR_TIMELINE_TWO = 2;
const CALENDAR_TIMELINE_THREE = 3;
const CALENDAR_TIMELINE_FOUR = 4;
const CALENDAR_TIMELINE_FIVE = 5;
const CALENDAR_TIMELINE_OTHER = 6; // không đồng ý với thời gian

const CALENDAR_TIMELINE = [
    CALENDAR_TIMELINE_ONE,
    CALENDAR_TIMELINE_TWO,
    CALENDAR_TIMELINE_THREE,
    CALENDAR_TIMELINE_FOUR,
    CALENDAR_TIMELINE_FIVE,
    CALENDAR_TIMELINE_OTHER
];

//hr-organization table
const COUNTRY = [
    '1' => 'ベトナム',
    '2' => 'ミャンマー',
    '3' => 'フィリピン ',
    '7' => 'タイ',
];

const ACC_CLASS_OWN_PLATFORM = 1;
const ACC_CLASS_SEND_AGENCY = 2;
const ACC_CLASS_DISPATCH_AGENCY = 3;
const ACC_CLASS_SCHOOL = 4;
const ACC_CLASS_COMPANY = 5;

//user_favorite table
const FAVORITE_TYPE_HRS = 1;
const FAVORITE_TYPE_WORK = 2;

// entries file type
const MOTIVATION_FILE = 1;
const RECOMMENDATION_FILE = 2;
const OTHER_FILE = 3;
const ENTRIES_FILE_TYPES = [
    MOTIVATION_FILE,
    RECOMMENDATION_FILE,
    OTHER_FILE,
];

const JOB_TYPE_COL_1 = 1;
const JOB_TYPE_COL_2 = 2;

const TEXT_MONING = '午前';
const TEXT_AFTERNOON = '午後';
const TEXT_TIME = '時';
const TEXT_MINUTE = '分';

//const TEXT_MONING = 'Sang';
//const TEXT_AFTERNOON = 'Chieu';
//const TEXT_TIME = 'Gio';
//const TEXT_MINUTE = 'Phut';

const NOTIFY_FOR_COMPANY = 1;
const NOTIFY_FOR_HR = 2;
const NOTIFY_FOR_MANAGER = 3;

const NAV_TAB_ENTRY = 'entry';
const NAV_TAB_OFFER = 'offer';
const NAV_TAB_INTERVIEW = 'interview';
const NAV_TAB_RESULT = 'result';

const NOTI_TYPE_ENTRY = 1;
const NOTI_TYPE_OFFER = 2;
const NOTI_TYPE_INTERVIEW = 3;
const NOTI_TYPE_RESULT = 4;
const NOTI_TYPE_ACCOUNT = 5;
const NOTI_TYPE_REMIND_ENTRY = 6;
const NOTI_TYPE_REMIND_OFFER = 7;
const NOTI_TYPE_REMIND_INTERVIEW = 8;
const NOTI_TYPE_REMIND_RESULT = 9;
