<?php

namespace Repository;

use App\Jobs\RemindAccountJob;
use App\Models\Company;
use App\Models\JobType;
use App\Models\User;
use App\Notifications\SendNotification;
use App\Repositories\Contracts\CompanyRepositoryInterface;
use Helper\Common;
use Helper\ResponseService;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Str;
use Tymon\JWTAuth\Facades\JWTAuth;

class CompanyRepository extends BaseRepository implements CompanyRepositoryInterface
{
    public function __construct(Application $app)
    {
        parent::__construct($app);
    }

    /**
     * Instantiate model
     *
     * @param Company $model
     */

    public function model()
    {
        return Company::class;
    }

    public function getAll($request)
    {
        $data = $this->with(['jobType', 'job']);
        if ($request->has('field') && $request->field) {
            if ($request->field == 'status'){
                $data = Common::sortArrayText($data, "status", User::listStatus(), $request->sort_by == 'asc');
            }elseif($request->field == 'field'){
                $jobType = JobType::query()->where('type',JOB_TYPE)->pluck('name_ja', 'id')->toArray();
                $data = Common::sortArrayText($data, "major_classification", $jobType, $request->sort_by == 'asc');
            }else{
                $data = Common::sortBy($request, $data);
            }
        }else{
            $data = $data->orderBy('id', 'desc');
        }
        return Common::pagination($request, $data);
    }

    public function update(array $attributes, $id)
    {
        return parent::update($attributes, $id); // TODO: Change the autogenerated stub
    }


    public function create(array $attributes)
    {
        if($attributes['is_create']) {
            $attributes['status'] = EXAMINATION_PENDING;
            $data = parent::create($attributes);
            RemindAccountJob::dispatch(COMPANY_MANAGER, Company::class, $data->id);
            return $data;
        }
        return;
    }

    public function getAllName()
    {
        if(Auth::user()->type == \COMPANY) {
            return $this->model->where('status', CONFIRM)
                ->whereNotNull('user_id')
                ->where(Company::USER_ID, Auth::id())
                ->get();
        }

        return $this->model->where('status', CONFIRM)
            ->whereNotNull('user_id')
            ->get();
    }
}
