<?php
/**
 * Created by VeHo.
 * Year: 2023-07-04
 */

namespace Repository;

use App\Jobs\CacheShiftList;
use App\Jobs\NotificationDistributionJob;
use App\Models\Notification;
use App\Models\UploadFile;
use App\Notifications\DistributionNotification;
use App\Repositories\Contracts\NotificationRepositoryInterface;
use Carbon\Carbon;
use Repository\BaseRepository;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Auth;

class NotificationRepository extends BaseRepository implements NotificationRepositoryInterface
{

     public function __construct(Application $app)
     {
         parent::__construct($app);

     }

    /**
       * Instantiate model
       *
       * @param Notification $model
       */

    public function model()
    {
        return Notification::class;
    }

    public function create(array $attributes)
    {
        $authUser = Auth::user();
        $image = UploadFile::find($attributes['image_id']);
        $urlImage = $image?$image->file_path:null;
        $reloadCache = NotificationDistributionJob::dispatch($authUser,$attributes['title'],$attributes['text'],$urlImage);

    }

    public function update(array $attributes, $id)
    {
        $attributes['read_at'] = Carbon::now();
        return parent::update($attributes, $id); // TODO: Change the autogenerated stub
    }


}
